title: STAT 5
description: Learn STAT 5 here!
theme: just-the-docs

url: https://kxtherinee.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
